name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    env:
      LT_USERNAME: "username"
      LT_ACCESS_KEY: "accesskey"
    strategy:
      max-parallel: 5

    steps:
    - name: Pull LambdaTest Tunnel Docker Image
      run: docker pull lambdatest/tunnel:latest

    - name: Verify LambdaTest Tunnel Version
      run: docker run --rm lambdatest/tunnel --version

    - name: Start LambdaTest Tunnel
      run: |
        docker run -d --name lt lambdatest/tunnel --user <username> --key <accesskey>

        
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
        
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH

    - name: Lint with flake8
      run: |
        conda install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        conda install pytest
        pip install -r requirements.txt
        make test_ios1
